### ISSUE TITLE
Flash-Next: sparse prefill kernel fails to compile on macOS 27 (mlx 0.32.2 + MPP SDK) → HTTP 500 on 33K+ prompts

### ISSUE THREAD

**Issue by sunnybluesea** [youssofal/MTPLX#404]
## Environment
- MTPLX 2.10.1 (pip, python3.11)
- mlx 0.32.2 / mlx-metal 0.32.2
- macOS 27.0 (SDK 27.0), M5 Max 128GB
- Model: Qwen3.8-Flash-Next-MTPLX-Optimized-Speed (qwen4_exp, turbo profile)

## Symptom
Any request with history past ~33K tokens fails with HTTP 500. Error from server log:

```
[metal::Device] Unable to build metal library from source
mlx/backend/metal/kernels/utils.h:560:31: error: no matching member function for call to 'get_destination_cooperative_tensor'
auto accumulator = matmul.get_destination_cooperative_tensor<
MPPTensorOpsMatMul2d.h:562:3: note: candidate template ignored: requirement 'false' was not satisfied
[with LeftOperandType = thread metal::cooperative_tensor<bfloat, metal::extents<int, 18446744073709551615, 18446744073709551615>, ...>]
```

Triggered kernel: `custom_kernel_mtplx_qsa_prefill_mpp_scores_h4d128` (the new 2.10.1 sparse prefill lane).

## Repro
1. Start: `mtplx quickstart --model Qwen3.8-Flash-Next-MTPLX-Optimized-Speed --mtp --profile turbo --port 8003`
2. POST a chat completion with a ~72K-token prompt (140K chars):
   → HTTP 500 after ~25s; server compiles the qsa_prefill_mpp_scores kernel and fails.

With `MTPLX_QSA_PREFILL=0` the same request succeeds (85.8s, dense path). So the failure is isolated to the sparse prefill lane.

## Root cause analysis
The kernel calls `get_destination_cooperative_tensor<...>()` from `mlx/backend/metal/kernels/steel/gemm/nax.h` (mlx 0.32.2) with dynamic extents (`extents<int, UINT64_MAX, UINT64_MAX>`, i.e. 18446744073709551615). On macOS 27 the MetalPerformancePrimitives headers (MPPTensorOpsMatMul2d.h:556-562) gate the template on `__is_tensor_type_v<LeftOperandType> || __is_cooperative_tensor_type_v<LeftOperandType>` and reject this instantiation (requirement 'false').

mlx 0.32.2 is the latest release (2026-08-25) and pins MTPLX 2.10.1 via `mlx<0.33,>=0.32.2`. The 2.10.1 release notes list the sparse-prefill measurements taken on macOS 26; this looks like a macOS 27 SDK break with the cooperative-tensor API.

## Workaround (local)
`export MTPLX_QSA_PREFILL=0` — loses the 35% long-prompt speedup.

## Questions
1. Was sparse prefill validated on macOS 27? (Release notes mention macOS 26.)
2. Is there a planned mlx bump or kernel fix (fixed-size extents / version-gated MPP path) for macOS 27?
3. Could the lane detect the compile failure at startup and fall back to the dense path automatically instead of returning HTTP 500 mid-request?

**Comment by DigiJoe79** [comment]
I have the same Issue (https://github.com/youssofal/MTPLX/issues/405) and closed mine as duplicate.

**Comment by mrmurphy** [comment]
Same error here on macOS 27 (M5 Max) with mtplx 2.10.1 + mlx 0.32.2 — reproduced deterministically on long prefills with `custom_kernel_mtplx_qsa_prefill_mpp_scores_h4d128`.

DeepSeek tracked it down and applied a one-line local workaround that preserves the sparse-prefill speedup (no need for `MTPLX_QSA_PREFILL=0`): [Caveat that I don't personally understand this code]

**File:** `mtplx/kernels/qsa_indexer_prefill.py`, inside `_MPP_SCORE_SOURCE`, the call:
```metal
auto accumulator = matmul.get_destination_cooperative_tensor<
    decltype(left), decltype(right), float>();
```
**Fix** — strip the address-space qualifier on the operands (matching how mlx's own NAX kernels call it in `steel/gemm/nax.h`):
```metal
auto accumulator = matmul.get_destination_cooperative_tensor<
    metal::remove_addrspace_t<decltype(left)>,
    metal::remove_addrspace_t<decltype(right)>, float>();
```
With that change the kernel cold-compiles and runs fine and is bit-identical to the reference path (bf16 & fp16). So on macOS 27 the MPP header rejects the address-space-qualified operand types (`thread cooperative_tensor<...>` → `requirement 'false'`), rather than this being a fundamental SDK break.

Huge thanks to the @youssofal for the impressive work on MTPLX, and to @sunnybluesea for filing the report.

**Comment by sunnybluesea** [comment]
Update from the original reporter (macOS 27, M5 Max 128GB):

@mrmurphy's one-line workaround works for the mpp_scores kernel, but after applying it I hit a SECOND kernel with the same failure, and a third one to be safe. On macOS 27, **all three** sparse-prefill kernels that call `get_destination_cooperative_tensor<decltype(...), decltype(...), float>()` without `remove_addrspace_t` fail to compile:

1. `mtplx/kernels/qsa_indexer_prefill.py` — `custom_kernel_mtplx_qsa_prefill_mpp_scores_h4d128` (the one @mrmurphy fixed)
2. `mtplx/kernels/qsa_prefill_flash.py:137` — `custom_kernel_mtplx_qsa_prefill_flash_nax_m16_n32_h24_kv2_d256_b4_k512` (hit next)
3. `mtplx/kernels/sdpa_nax_tile.py:100` — the NAX SDPA tile kernel (patched pre-emptively)

Applying `metal::remove_addrspace_t<...>` to all three (same pattern as @mrmurphy's fix) resolves it completely. Verified on M5 Max 128GB / macOS 27 / mlx 0.32.2 / mtplx 2.10.1:

| prompt | before | after fix |
|---|---|---|
| 70K tokens | HTTP 500 (kernel compile fail) | 64.4s ✅ |
| 95K tokens | HTTP 500 | 84.9s ✅ |

That's ~25-28% faster than the dense path (`MTPLX_QSA_PREFILL=0` baseline was 85.2s for 72K tokens) — the sparse lane is working as advertised and bit-stable on long prompts. Results were consistent across two runs.

Suggest the 2.10.2 release either apply `remove_addrspace_t` in all three call sites, or better, probe the GPU/MPP SDK at startup and emit a clear diagnostic instead of a raw kernel compile failure. Thanks again for the impressive work!

**Comment by youssofal** [comment]
Root caused. The macOS 27 MPP SDK changed the cooperative tensor template surface and three call sites in the sparse prefill kernels no longer compile against it, which is why every prompt past the 32k engagement line answers 500. The fix is built and validated on our rig: the kernel sites compile on both SDK generations, and a failed kernel build now falls back to the dense path with a diagnostic instead of a 500. It missed the 2.10.2 cut and ships in the next release. #407 is the same failure reached through Pi.

Until then, set MTPLX_QSA_PREFILL=0 in the server environment to force the dense prefill path on macOS 27. Slower past 32k, but every prompt length works.

**Comment by DigiJoe79** [comment]
Thanks @youssofal - Really appreciate your work. mtPLX is an amazing project :)

**Comment by youssofal** [comment]
The fix is in 2.11.1. All seven cooperative-tensor sites (the three sparse-prefill kernels and the four on the 27B flash-decoding route) use the address-space-neutral operand types, and the server dispatches the real sparse-prefill pipeline once at startup, so an SDK that refuses it degrades to dense prefill with a diagnostic instead of a mid-request 500. Credit to @mrmurphy for the first working patch and to you for the root cause, the three-site sweep and the macOS 27 receipts. Verified here on macOS 26 with the kernel parity suites; a macOS 27 confirmation on 2.11.1 from any of you would close the loop. Release: https://github.com/youssofal/MTPLX/releases/tag/v2.11.1
